## Processing Scraped NBA Data

In [71]:
import pandas as pd
import numpy as np

In [72]:
#Import data and remove irrelevant columns
file = 'C:\\Users\\Chung-Tseng Wang\\Desktop\\Github Repo\\Predicting-NBA-Rookie-Stats\\data\\raw\\nba_stats_raw.csv'
raw = pd.read_csv(file)
raw = raw.drop(['Debut','MP','FG','FGA','3P','FT','FTA','ORB','TRB','AST','PF'],axis = 1)
raw.head()

,year,Player,id,Age,Yrs,G,3PA,STL,BLK,TOV,PTS,FG%,3P%,FT%,MP.1,PS/G,TRB/G,AST/G
0,2019,Jaylen Adams,adamsja01,22,1,34,74,14,5,28,108,0.345,0.338,0.778,12.6,3.2,1.8,1.9
1,2019,Deng Adel,adelde01,21,1,19,23,1,4,6,32,0.306,0.261,1.000,10.2,1.7,1.0,0.3
2,2019,DeVaughn Akoon-Purcell,akoonde01,25,1,7,4,2,0,2,7,0.300,0.000,0.500,3.1,1.0,0.6,0.9
3,2019,Rawle Alkins,alkinra01,21,1,10,12,1,0,8,37,0.333,0.250,0.667,12.0,3.7,2.6,1.3
4,2019,Grayson Allen,allengr01,23,1,38,99,6,6,33,211,0.376,0.323,0.750,10.9,5.6,0.6,0.7

In [73]:
#Calculate steals, blocks, and turnover per game
raw['STL/G'] = raw['STL'] / raw['G']
raw['BLK/G'] = raw['BLK'] / raw['G']
raw['TOV/G'] = raw['TOV'] / raw['G']
raw = raw.drop(['Yrs','3PA','STL','BLK','TOV','PTS','MP.1','id'], axis = 1)
raw.head()

,year,Player,Age,G,FG%,3P%,FT%,PS/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G
0,2019,Jaylen Adams,22,34,0.345,0.338,0.778,3.2,1.8,1.9,0.411765,0.147059,0.823529
1,2019,Deng Adel,21,19,0.306,0.261,1.000,1.7,1.0,0.3,0.052632,0.210526,0.315789
2,2019,DeVaughn Akoon-Purcell,25,7,0.300,0.000,0.500,1.0,0.6,0.9,0.285714,0.000000,0.285714
3,2019,Rawle Alkins,21,10,0.333,0.250,0.667,3.7,2.6,1.3,0.100000,0.000000,0.800000
4,2019,Grayson Allen,23,38,0.376,0.323,0.750,5.6,0.6,0.7,0.157895,0.157895,0.868421

In [74]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 13 columns):
year      892 non-null int64
Player    892 non-null object
Age       892 non-null int64
G         892 non-null int64
FG%       885 non-null float64
3P%       809 non-null float64
FT%       830 non-null float64
PS/G      892 non-null float64
TRB/G     892 non-null float64
AST/G     892 non-null float64
STL/G     892 non-null float64
BLK/G     892 non-null float64
TOV/G     892 non-null float64
dtypes: float64(9), int64(3), object(1)
memory usage: 90.7+ KB

In [75]:
raw.describe()

,year,Age,G,FG%,3P%,FT%,PS/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G
count,892.000000,892.000000,892.000000,885.000000,809.000000,830.000000,892.000000,892.000000,892.000000,892.000000,892.000000,892.000000
mean,2014.576233,22.394619,176.522422,0.424284,0.283958,0.710528,6.112108,2.755942,1.331951,0.502463,0.314686,0.877862
std,3.160115,2.214911,195.737205,0.107532,0.137368,0.150213,4.572743,1.998254,1.324058,0.352847,0.356438,0.643992
min,2009.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2012.000000,21.000000,24.750000,0.387000,0.238000,0.644750,2.900000,1.400000,0.500000,0.250000,0.079928,0.440508
50%,2015.000000,22.000000,94.000000,0.429000,0.319000,0.738000,5.100000,2.300000,0.900000,0.435573,0.209730,0.754005
75%,2018.000000,24.000000,270.000000,0.473000,0.359000,0.800000,8.000000,3.600000,1.800000,0.694420,0.431773,1.154541
max,2019.000000,35.000000,821.000000,1.000000,1.000000,1.000000,24.300000,13.700000,9.200000,1.925703,2.439394,4.051157

In [76]:
raw.isna().sum()

year       0
Player     0
Age        0
G          0
FG%        7
3P%       83
FT%       62
PS/G       0
TRB/G      0
AST/G      0
STL/G      0
BLK/G      0
TOV/G      0
dtype: int64

In [77]:
raw['FG%'].fillna((raw['FG%'].mean()),inplace = True)
raw['3P%'].fillna((raw['3P%'].mean()),inplace = True)
raw['FT%'].fillna((raw['FT%'].mean()),inplace = True)
raw.head()

,year,Player,Age,G,FG%,3P%,FT%,PS/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G
0,2019,Jaylen Adams,22,34,0.345,0.338,0.778,3.2,1.8,1.9,0.411765,0.147059,0.823529
1,2019,Deng Adel,21,19,0.306,0.261,1.000,1.7,1.0,0.3,0.052632,0.210526,0.315789
2,2019,DeVaughn Akoon-Purcell,25,7,0.300,0.000,0.500,1.0,0.6,0.9,0.285714,0.000000,0.285714
3,2019,Rawle Alkins,21,10,0.333,0.250,0.667,3.7,2.6,1.3,0.100000,0.000000,0.800000
4,2019,Grayson Allen,23,38,0.376,0.323,0.750,5.6,0.6,0.7,0.157895,0.157895,0.868421

In [78]:
raw.isna().sum()

year      0
Player    0
Age       0
G         0
FG%       0
3P%       0
FT%       0
PS/G      0
TRB/G     0
AST/G     0
STL/G     0
BLK/G     0
TOV/G     0
dtype: int64

In [79]:
from unidecode import unidecode
raw['Player'] = raw['Player'].apply(unidecode)
raw.head()

,year,Player,Age,G,FG%,3P%,FT%,PS/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G
0,2019,Jaylen Adams,22,34,0.345,0.338,0.778,3.2,1.8,1.9,0.411765,0.147059,0.823529
1,2019,Deng Adel,21,19,0.306,0.261,1.000,1.7,1.0,0.3,0.052632,0.210526,0.315789
2,2019,DeVaughn Akoon-Purcell,25,7,0.300,0.000,0.500,1.0,0.6,0.9,0.285714,0.000000,0.285714
3,2019,Rawle Alkins,21,10,0.333,0.250,0.667,3.7,2.6,1.3,0.100000,0.000000,0.800000
4,2019,Grayson Allen,23,38,0.376,0.323,0.750,5.6,0.6,0.7,0.157895,0.157895,0.868421

In [80]:
raw = raw.rename(columns = {'G':'NBA_G','FG%':'NBA_FGP','3P%':'NBA_3PP','FT%':'NBA_FTP','PS/G':'NBA_PTS','TRB/G':'NBA_TRB','AST/G':'NBA_AST','STL/G':'NBA_STL','BLK/G':'NBA_BLK','TOV/G':'NBA_TOV'})
raw.head()

,year,Player,Age,NBA_G,NBA_FGP,NBA_3PP,NBA_FTP,NBA_PTS,NBA_TRB,NBA_AST,NBA_STL,NBA_BLK,NBA_TOV
0,2019,Jaylen Adams,22,34,0.345,0.338,0.778,3.2,1.8,1.9,0.411765,0.147059,0.823529
1,2019,Deng Adel,21,19,0.306,0.261,1.000,1.7,1.0,0.3,0.052632,0.210526,0.315789
2,2019,DeVaughn Akoon-Purcell,25,7,0.300,0.000,0.500,1.0,0.6,0.9,0.285714,0.000000,0.285714
3,2019,Rawle Alkins,21,10,0.333,0.250,0.667,3.7,2.6,1.3,0.100000,0.000000,0.800000
4,2019,Grayson Allen,23,38,0.376,0.323,0.750,5.6,0.6,0.7,0.157895,0.157895,0.868421

In [81]:
raw.to_csv('processed_nba.csv',index = True)

## Processing Scraped College Data

In [82]:
raw_c = pd.read_csv('C:\\Users\\Chung-Tseng Wang\\Desktop\\Github Repo\\Predicting-NBA-Rookie-Stats\\data\\raw\\college_stats_raw.csv') 
raw_c.head()

,Player,School,G,FGP,3P%,FTP,TRB,AST,STL,BLK,TOV,PTS
0,Jaylen Adams,St. Bonaventure,110,0.427,0.394,0.838,3.4,5.4,1.5,0.2,2.9,17.4
1,Deng Adel,Louisville,89,0.438,0.348,0.776,4.1,2.0,0.5,0.3,1.7,11.2
2,DeVaughn Akoon-Purcell,Illinois State,60,0.428,0.301,0.739,5.3,1.6,1.0,0.3,2.3,13.5
3,Rawle Alkins,Arizona,60,0.450,0.365,0.729,4.9,2.2,1.0,0.6,2.1,11.8
4,Grayson Allen,Duke,142,0.430,0.380,0.834,3.2,3.0,1.0,0.1,1.7,14.1

In [83]:
raw_c.describe()

,G,FGP,3P%,FTP,TRB,AST,STL,BLK,TOV,PTS
count,732.000000,731.000000,680.000000,730.000000,732.000000,732.000000,732.000000,732.000000,721.000000,732.000000
mean,89.112022,0.475057,0.333596,0.711530,5.091120,2.086612,0.980328,0.728279,1.883079,12.044262
std,39.086855,0.068107,0.127358,0.104518,2.201862,1.483898,0.504232,0.726332,0.733895,4.383323
min,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,61.000000,0.433500,0.308000,0.663250,3.500000,1.000000,0.600000,0.200000,1.400000,9.400000
50%,95.000000,0.463000,0.350000,0.729000,4.800000,1.700000,0.900000,0.500000,1.800000,12.200000
75%,128.000000,0.517000,0.381250,0.780000,6.400000,2.900000,1.300000,1.000000,2.300000,14.825000
max,152.000000,0.692000,1.000000,1.000000,12.400000,8.700000,2.900000,5.400000,5.400000,27.500000

In [84]:
raw_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 12 columns):
Player    732 non-null object
School    732 non-null object
G         732 non-null int64
FGP       731 non-null float64
3P%       680 non-null float64
FTP       730 non-null float64
TRB       732 non-null float64
AST       732 non-null float64
STL       732 non-null float64
BLK       732 non-null float64
TOV       721 non-null float64
PTS       732 non-null float64
dtypes: float64(9), int64(1), object(2)
memory usage: 68.7+ KB

In [85]:
raw_c.isna().sum()

Player     0
School     0
G          0
FGP        1
3P%       52
FTP        2
TRB        0
AST        0
STL        0
BLK        0
TOV       11
PTS        0
dtype: int64

In [86]:
raw_c['FGP'].fillna((raw_c['FGP'].mean()),inplace = True)
raw_c['3P%'].fillna((raw_c['3P%'].mean()),inplace = True)
raw_c['FTP'].fillna((raw_c['FTP'].mean()),inplace = True)
raw_c['TOV'].fillna((raw_c['TOV'].mean()),inplace = True)

In [87]:
raw_c.isna().sum()

Player    0
School    0
G         0
FGP       0
3P%       0
FTP       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PTS       0
dtype: int64

In [88]:
raw_c['Player'] = raw_c['Player'].apply(unidecode)
raw_c.head()

,Player,School,G,FGP,3P%,FTP,TRB,AST,STL,BLK,TOV,PTS
0,Jaylen Adams,St. Bonaventure,110,0.427,0.394,0.838,3.4,5.4,1.5,0.2,2.9,17.4
1,Deng Adel,Louisville,89,0.438,0.348,0.776,4.1,2.0,0.5,0.3,1.7,11.2
2,DeVaughn Akoon-Purcell,Illinois State,60,0.428,0.301,0.739,5.3,1.6,1.0,0.3,2.3,13.5
3,Rawle Alkins,Arizona,60,0.450,0.365,0.729,4.9,2.2,1.0,0.6,2.1,11.8
4,Grayson Allen,Duke,142,0.430,0.380,0.834,3.2,3.0,1.0,0.1,1.7,14.1

In [89]:
raw_c = raw_c.rename(columns = {'G':'c_G','FGP':'c_FGP','3P%':'c_3PP','FTP':'c_FTP','PTS':'c_PTS','TRB':'c_TRB','AST':'c_AST','STL':'c_STL','BLK':'c_BLK','TOV':'c_TOV'})
raw_c.head()

,Player,School,c_G,c_FGP,c_3PP,c_FTP,c_TRB,c_AST,c_STL,c_BLK,c_TOV,c_PTS
0,Jaylen Adams,St. Bonaventure,110,0.427,0.394,0.838,3.4,5.4,1.5,0.2,2.9,17.4
1,Deng Adel,Louisville,89,0.438,0.348,0.776,4.1,2.0,0.5,0.3,1.7,11.2
2,DeVaughn Akoon-Purcell,Illinois State,60,0.428,0.301,0.739,5.3,1.6,1.0,0.3,2.3,13.5
3,Rawle Alkins,Arizona,60,0.450,0.365,0.729,4.9,2.2,1.0,0.6,2.1,11.8
4,Grayson Allen,Duke,142,0.430,0.380,0.834,3.2,3.0,1.0,0.1,1.7,14.1

In [90]:
raw_c.to_csv('processed_college.csv',index = True)

In [91]:
nba_college = raw.merge(raw_c,on = 'Player', how = 'left')
nba_college.head()

,year,Player,Age,NBA_G,NBA_FGP,NBA_3PP,NBA_FTP,NBA_PTS,NBA_TRB,NBA_AST,...,c_G,c_FGP,c_3PP,c_FTP,c_TRB,c_AST,c_STL,c_BLK,c_TOV,c_PTS
0,2019,Jaylen Adams,22,34,0.345,0.338,0.778,3.2,1.8,1.9,...,110.0,0.427,0.394,0.838,3.4,5.4,1.5,0.2,2.9,17.4
1,2019,Deng Adel,21,19,0.306,0.261,1.000,1.7,1.0,0.3,...,89.0,0.438,0.348,0.776,4.1,2.0,0.5,0.3,1.7,11.2
2,2019,DeVaughn Akoon-Purcell,25,7,0.300,0.000,0.500,1.0,0.6,0.9,...,60.0,0.428,0.301,0.739,5.3,1.6,1.0,0.3,2.3,13.5
3,2019,Rawle Alkins,21,10,0.333,0.250,0.667,3.7,2.6,1.3,...,60.0,0.450,0.365,0.729,4.9,2.2,1.0,0.6,2.1,11.8
4,2019,Grayson Allen,23,38,0.376,0.323,0.750,5.6,0.6,0.7,...,142.0,0.430,0.380,0.834,3.2,3.0,1.0,0.1,1.7,14.1

In [92]:
nba_college.columns

Index(['year', 'Player', 'Age', 'NBA_G', 'NBA_FGP', 'NBA_3PP', 'NBA_FTP',
       'NBA_PTS', 'NBA_TRB', 'NBA_AST', 'NBA_STL', 'NBA_BLK', 'NBA_TOV',
       'School', 'c_G', 'c_FGP', 'c_3PP', 'c_FTP', 'c_TRB', 'c_AST', 'c_STL',
       'c_BLK', 'c_TOV', 'c_PTS'],
      dtype='object')

In [93]:
nba_college.isna().sum()

year         0
Player       0
Age          0
NBA_G        0
NBA_FGP      0
NBA_3PP      0
NBA_FTP      0
NBA_PTS      0
NBA_TRB      0
NBA_AST      0
NBA_STL      0
NBA_BLK      0
NBA_TOV      0
School     160
c_G        160
c_FGP      160
c_3PP      160
c_FTP      160
c_TRB      160
c_AST      160
c_STL      160
c_BLK      160
c_TOV      160
c_PTS      160
dtype: int64

In [94]:
final[final['School'].isnull()]

,year,Player,Age,NBA_G,NBA_FGP,NBA_3PP,NBA_FTP,NBA_PTS,NBA_TRB,NBA_AST,...,c_G,c_FGP,c_3PP,c_FTP,c_TRB,c_AST,c_STL,c_BLK,c_TOV,c_PTS
7,2019,Marvin Bagley,19,62,0.504,0.313000,0.691000,14.9,7.6,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2019,Dairis Bertans,29,12,0.255,0.294000,0.710528,2.8,0.8,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2019,Isaac Bonga,19,22,0.152,0.000000,0.600000,0.9,1.1,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2019,Mitch Creek,26,5,0.500,0.000000,0.714000,4.2,2.4,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2019,Angel Delgado,24,2,0.200,0.283958,0.500000,1.5,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2019,Luka Doncic,19,72,0.427,0.327000,0.713000,21.2,7.8,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2019,Isaiah Hartenstein,20,28,0.488,0.333000,0.786000,1.9,1.7,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2019,Haywood Highsmith,22,5,0.400,0.200000,0.000000,1.8,1.0,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,2019,Rodions Kurucs,20,63,0.450,0.315000,0.783000,8.5,3.9,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,2019,Shake Milton,22,20,0.391,0.318000,0.714000,4.4,1.8,0.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,2019,Dzanan Musa,19,9,0.409,0.100000,0.000000,2.1,0.6,0.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,2019,Elie Okobo,21,53,0.393,0.295000,0.787000,5.7,1.8,2.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,2019,Mitchell Robinson,20,66,0.694,0.283958,0.600000,7.3,6.4,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,2019,Anfernee Simons,19,20,0.444,0.345000,0.563000,3.8,0.7,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2019,Ray Spalding,21,14,0.532,0.000000,0.333000,3.9,3.4,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,2019,Emanuel Terry,22,3,0.571,0.283958,0.500000,3.3,2.3,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2019,Lonnie Walker,20,17,0.348,0.385000,0.800000,2.6,1.0,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,2018,Bam Adebayo,20,151,0.550,0.136000,0.728000,8.0,6.5,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,2018,Bogdan Bogdanovic,25,148,0.431,0.375000,0.833000,12.9,3.1,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,2018,Terrance Ferguson,19,135,0.425,0.356000,0.754000,5.2,1.4,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,2018,Maxi Kleber,26,143,0.469,0.338000,0.767000,6.1,3.9,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2018,Furkan Korkmaz,20,62,0.388,0.323000,0.792000,4.9,1.9,0.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,2018,Walt Lemon,25,11,0.437,0.500000,0.714000,9.4,2.6,3.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,2018,Josh Magette,28,18,0.326,0.364000,1.000000,2.6,1.1,3.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,2018,Naz Mitrou-Long,24,15,0.333,0.250000,1.000000,1.3,0.4,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,2018,Jaylen Morris,22,10,0.405,0.231000,0.500000,3.8,2.1,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,2018,Frank Ntilikina,19,121,0.354,0.305000,0.735000,5.9,2.2,3.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,2018,Cedi Osman,22,137,0.437,0.351000,0.736000,9.0,3.5,1.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,2018,Zhou Qi,22,19,0.212,0.105000,0.667000,1.3,1.2,0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,2018,Milos Teodosic,30,60,0.420,0.378000,0.811000,8.0,2.4,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,2011,Timofey Mozgov,24,454,0.535,0.190000,0.738000,6.8,4.9,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
758,2011,Nikola Pekovic,25,271,0.518,0.283958,0.760000,12.6,6.7,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
764,2011,Kevin Seraphin,21,423,0.489,0.000000,0.715000,5.9,3.5,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766,2011,Garret Siler,24,21,0.548,0.283958,0.500000,2.1,1.3,0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
767,2011,Ish Smith,22,542,0.427,0.306000,0.678000,7.4,2.4,3.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
768,2011,Tiago Splitter,26,355,0.555,0.143000,0.697000,7.9,5.0,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
770,2011,Pape Sy,22,3,0.333,0.000000,1.000000,2.3,1.0,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,2011,Greivis Vasquez,24,401,0.418,0.349000,0.817000,9.0,2.5,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
778,2010,David Andersen,29,103,0.440,0.347000,0.674000,4.9,2.8,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
780,2010,Jeff Ayres,22,237,0.553,0.400000,0.776000,2.9,2.7,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
781,2010,Rodrigue Beaubois,21,182,0.439,0.325000,0.810000,7.1,1.9,2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
787,2010,Omri Casspi,21,588,0.454,0.368000,0.678000,7.9,4.0,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
807,2010,Gerald Henderson,22,535,0.440,0.327000,0.793000,11.2,3.2,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
812,2010,Serge Ibaka,20,753,0.514,0.357000,0.761000,12.3,7.3,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
816,2010,Jonas Jerebko,22,635,0.457,0.363000,0.770000,6.2,4.0,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
824,2010,Patty Mills,21,605,0.431,0.391000,0.849000,8.4,1.7,2.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
825,2010,Byron Mullens,20,189,0.408,0.319000,0.706000,7.4,4.2,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836,2009,Alexis Ajinca,20,293,0.503,0.286000,0.797000,5.3,3.9,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
841,2009,Nicolas Batum,20,767,0.435,0.358000,0.841000,11.8,5.3,3.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
849,2009,Goran Dragic,22,758,0.466,0.363000,0.762000,13.7,3.1,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
850,2009,Rudy Fernandez,23,249,0.399,0.360000,0.840000,9.1,2.4,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
851,2009,Danilo Gallinari,20,549,0.425,0.376000,0.871000,15.9,4.9,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
852,2009,Marc Gasol,24,795,0.483,0.350000,0.777000,15.0,7.7,3.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
855,2009,Donte Greene,20,253,0.406,0.304000,0.701000,6.1,2.4,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
856,2009,Hamed Haddadi,23,151,0.463,0.000000,0.632000,2.2,2.5,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
864,2009,Nathan Jawai,22,45,0.435,0.000000,0.684000,2.8,2.4,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,2009,Luc Mbah a Moute,22,686,0.454,0.335000,0.660000,6.4,4.1,0.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,2009,Roko Ukic,24,85,0.387,0.189000,0.746000,4.0,0.9,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,2009,Henry Walker,21,181,0.446,0.369000,0.760000,6.0,2.2,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,2009,Sun Yue,23,10,0.273,0.000000,0.710528,0.6,0.0,0.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
inter = pd.read_csv('C:\\Users\\Chung-Tseng Wang\\Desktop\\Github Repo\\Predicting-NBA-Rookie-Stats\\data\\Web Scraper\\International_stats\\processed_inter.csv')
inter.head()

,Player,c_FGP,c_3PP,c_FTP,c_TRB,c_AST,c_STL,c_BLK,c_TOV,c_PTS
0,Dairis Bertans,0.433,0.383,0.799,1.2,1.3,0.5,0.0,0.9,9.7
1,Luka Doncic,0.473,0.320,0.766,4.1,3.2,0.7,0.4,1.8,8.1
2,Rodions Kurucs,0.462,0.286,0.000,0.5,0.3,0.8,0.3,0.5,2.3
3,Elie Okobo,0.464,0.385,0.823,2.3,3.3,0.7,0.2,1.8,9.1
4,Terrance Ferguson,0.378,0.317,0.611,1.2,0.7,0.3,0.3,1.0,4.7

In [108]:
final = nba_college.merge(inter,left_on = ['Player','c_FGP', 'c_3PP', 'c_FTP', 'c_TRB', 'c_AST', 'c_STL',
       'c_BLK', 'c_TOV', 'c_PTS'],right_on = ['Player','c_FGP', 'c_3PP', 'c_FTP', 'c_TRB', 'c_AST', 'c_STL',
       'c_BLK', 'c_TOV', 'c_PTS'], how = 'left')
final[final['Player'] =='Luka Doncic']

,year,Player,Age,NBA_G,NBA_FGP,NBA_3PP,NBA_FTP,NBA_PTS,NBA_TRB,NBA_AST,...,c_G,c_FGP,c_3PP,c_FTP,c_TRB,c_AST,c_STL,c_BLK,c_TOV,c_PTS
35,2019,Luka Doncic,19,72,0.427,0.327,0.713,21.2,7.8,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for n in nba_college.columns:
    if n in list(inter.columns):

In [97]:
final.columns

Index(['year', 'Player', 'Age', 'NBA_G', 'NBA_FGP', 'NBA_3PP', 'NBA_FTP',
       'NBA_PTS', 'NBA_TRB', 'NBA_AST', 'NBA_STL', 'NBA_BLK', 'NBA_TOV',
       'School', 'c_G', 'c_FGP', 'c_3PP', 'c_FTP', 'c_TRB', 'c_AST', 'c_STL',
       'c_BLK', 'c_TOV', 'c_PTS'],
      dtype='object')

In [98]:
final.to_csv('final.csv',index = True)

In [101]:
final[final['c_PTS'].isnull()]

,year,Player,Age,NBA_G,NBA_FGP,NBA_3PP,NBA_FTP,NBA_PTS,NBA_TRB,NBA_AST,...,c_G,c_FGP,c_3PP,c_FTP,c_TRB,c_AST,c_STL,c_BLK,c_TOV,c_PTS
7,2019,Marvin Bagley,19,62,0.504,0.313000,0.691000,14.9,7.6,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2019,Dairis Bertans,29,12,0.255,0.294000,0.710528,2.8,0.8,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2019,Isaac Bonga,19,22,0.152,0.000000,0.600000,0.9,1.1,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2019,Mitch Creek,26,5,0.500,0.000000,0.714000,4.2,2.4,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2019,Angel Delgado,24,2,0.200,0.283958,0.500000,1.5,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2019,Luka Doncic,19,72,0.427,0.327000,0.713000,21.2,7.8,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2019,Isaiah Hartenstein,20,28,0.488,0.333000,0.786000,1.9,1.7,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2019,Haywood Highsmith,22,5,0.400,0.200000,0.000000,1.8,1.0,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,2019,Rodions Kurucs,20,63,0.450,0.315000,0.783000,8.5,3.9,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,2019,Shake Milton,22,20,0.391,0.318000,0.714000,4.4,1.8,0.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,2019,Dzanan Musa,19,9,0.409,0.100000,0.000000,2.1,0.6,0.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,2019,Elie Okobo,21,53,0.393,0.295000,0.787000,5.7,1.8,2.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,2019,Mitchell Robinson,20,66,0.694,0.283958,0.600000,7.3,6.4,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,2019,Anfernee Simons,19,20,0.444,0.345000,0.563000,3.8,0.7,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2019,Ray Spalding,21,14,0.532,0.000000,0.333000,3.9,3.4,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,2019,Emanuel Terry,22,3,0.571,0.283958,0.500000,3.3,2.3,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2019,Lonnie Walker,20,17,0.348,0.385000,0.800000,2.6,1.0,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,2018,Bam Adebayo,20,151,0.550,0.136000,0.728000,8.0,6.5,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,2018,Bogdan Bogdanovic,25,148,0.431,0.375000,0.833000,12.9,3.1,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,2018,Terrance Ferguson,19,135,0.425,0.356000,0.754000,5.2,1.4,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,2018,Maxi Kleber,26,143,0.469,0.338000,0.767000,6.1,3.9,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2018,Furkan Korkmaz,20,62,0.388,0.323000,0.792000,4.9,1.9,0.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,2018,Walt Lemon,25,11,0.437,0.500000,0.714000,9.4,2.6,3.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,2018,Josh Magette,28,18,0.326,0.364000,1.000000,2.6,1.1,3.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,2018,Naz Mitrou-Long,24,15,0.333,0.250000,1.000000,1.3,0.4,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,2018,Jaylen Morris,22,10,0.405,0.231000,0.500000,3.8,2.1,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,2018,Frank Ntilikina,19,121,0.354,0.305000,0.735000,5.9,2.2,3.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,2018,Cedi Osman,22,137,0.437,0.351000,0.736000,9.0,3.5,1.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,2018,Zhou Qi,22,19,0.212,0.105000,0.667000,1.3,1.2,0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,2018,Milos Teodosic,30,60,0.420,0.378000,0.811000,8.0,2.4,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,2011,Timofey Mozgov,24,454,0.535,0.190000,0.738000,6.8,4.9,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
758,2011,Nikola Pekovic,25,271,0.518,0.283958,0.760000,12.6,6.7,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
764,2011,Kevin Seraphin,21,423,0.489,0.000000,0.715000,5.9,3.5,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766,2011,Garret Siler,24,21,0.548,0.283958,0.500000,2.1,1.3,0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
767,2011,Ish Smith,22,542,0.427,0.306000,0.678000,7.4,2.4,3.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
768,2011,Tiago Splitter,26,355,0.555,0.143000,0.697000,7.9,5.0,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
770,2011,Pape Sy,22,3,0.333,0.000000,1.000000,2.3,1.0,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,2011,Greivis Vasquez,24,401,0.418,0.349000,0.817000,9.0,2.5,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
778,2010,David Andersen,29,103,0.440,0.347000,0.674000,4.9,2.8,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
780,2010,Jeff Ayres,22,237,0.553,0.400000,0.776000,2.9,2.7,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
781,2010,Rodrigue Beaubois,21,182,0.439,0.325000,0.810000,7.1,1.9,2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
787,2010,Omri Casspi,21,588,0.454,0.368000,0.678000,7.9,4.0,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
807,2010,Gerald Henderson,22,535,0.440,0.327000,0.793000,11.2,3.2,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
812,2010,Serge Ibaka,20,753,0.514,0.357000,0.761000,12.3,7.3,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
816,2010,Jonas Jerebko,22,635,0.457,0.363000,0.770000,6.2,4.0,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
824,2010,Patty Mills,21,605,0.431,0.391000,0.849000,8.4,1.7,2.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
825,2010,Byron Mullens,20,189,0.408,0.319000,0.706000,7.4,4.2,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836,2009,Alexis Ajinca,20,293,0.503,0.286000,0.797000,5.3,3.9,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
841,2009,Nicolas Batum,20,767,0.435,0.358000,0.841000,11.8,5.3,3.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
849,2009,Goran Dragic,22,758,0.466,0.363000,0.762000,13.7,3.1,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
850,2009,Rudy Fernandez,23,249,0.399,0.360000,0.840000,9.1,2.4,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
851,2009,Danilo Gallinari,20,549,0.425,0.376000,0.871000,15.9,4.9,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
852,2009,Marc Gasol,24,795,0.483,0.350000,0.777000,15.0,7.7,3.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
855,2009,Donte Greene,20,253,0.406,0.304000,0.701000,6.1,2.4,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
856,2009,Hamed Haddadi,23,151,0.463,0.000000,0.632000,2.2,2.5,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
864,2009,Nathan Jawai,22,45,0.435,0.000000,0.684000,2.8,2.4,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,2009,Luc Mbah a Moute,22,686,0.454,0.335000,0.660000,6.4,4.1,0.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,2009,Roko Ukic,24,85,0.387,0.189000,0.746000,4.0,0.9,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,2009,Henry Walker,21,181,0.446,0.369000,0.760000,6.0,2.2,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,2009,Sun Yue,23,10,0.273,0.000000,0.710528,0.6,0.0,0.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN